// <auto-generated />
namespace ProjectEssential.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BMITableCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BMITableCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710051301444_BMITableCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
